# Generated by Django 4.2.4 on 2023-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mandiprice_commodity_alter_mandiprice_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandiprice',
            name='commodity',
            field=models.CharField(choices=[('comm', 'Select Commodity'), ('rice', 'Rice'), ('wheat', 'Wheat'), ('corn', 'Corn'), ('barley', 'Barley'), ('potato', 'Potato'), ('tomato', 'Tomato'), ('onion', 'Onion'), ('carrot', 'Carrot'), ('apple', 'Apple'), ('banana', 'Banana'), ('orange', 'Orange'), ('strawberry', 'Strawberry')], default='Select Commodity', max_length=255, verbose_name='Commudity'),
        ),
    ]
