# Generated by Django 4.2.4 on 2023-09-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_market_commodity_alter_commodity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(blank=True, default='Select Commodity', max_length=255, null=True, verbose_name='Commodity'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(blank=True, default='Select Market', max_length=255, null=True, verbose_name='Market'),
        ),
        migrations.AlterField(
            model_name='market',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, default='Select State', max_length=255, null=True, verbose_name='State'),
        ),
    ]
