# Generated by Django 4.2.4 on 2023-09-01 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_commoditydata_avgprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditydata',
            name='commodity',
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 1, 16, 52, 0, 396077, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
