# Generated by Django 4.2.4 on 2023-09-05 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_commoditydata_commodity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditydata',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity'),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commodity'),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 5, 5, 9, 33, 662640, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
