# Generated by Django 4.2.4 on 2023-09-06 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_commoditydata_commodity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity'),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 15, 37, 28, 963902, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
