# Generated by Django 4.2.4 on 2023-09-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_commoditydata_priceupdated_alldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditydata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 19, 22, 19, 242701, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 19, 22, 19, 241702, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
