# Generated by Django 4.2.4 on 2023-09-06 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_commoditydata_location_alter_alldata_priceupdated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditydata',
            name='location',
        ),
        migrations.AddField(
            model_name='alldata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 19, 23, 59, 583922, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 19, 23, 59, 583922, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
